/*
 * Generated by utils/lexbor/css/gen_state_extra_header.py
 * Date: 2025-04-01 19:28:13
 * Do not edit manually!
 */

#ifndef LEXBOR_CSS_PROPERTY_STATE_EXTRA_H
#define LEXBOR_CSS_PROPERTY_STATE_EXTRA_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lexbor/css/parser.h"

LXB_API bool lxb_css_property_state_box_shadow(lxb_css_parser_t *parser, const lxb_css_syntax_token_t *token, void *ctx);

#ifdef __cplusplus
}
#endif

#endif /* LEXBOR_CSS_PROPERTY_STATE_EXTRA_H */