/*
 * Generated by utils/lexbor/css/gen_state_extra_header.py
 * Date: 2025-04-01 19:28:13
 * Do not edit manually!
 */

#include "lexbor/css/parser.h"

LXB_API bool lxb_css_property_state_box_shadow(lxb_css_parser_t *parser, const lxb_css_syntax_token_t *token, void *ctx);
LXB_API bool lxb_css_property_state_border_radius(lxb_css_parser_t *parser, lxb_css_syntax_token_t *token, void *ctx);